### ISSUE TITLE
What's the correct way to detect whether scanner is attached or not?

### ISSUE THREAD

**Issue by jonaszuberbuehler** [InfinitePeripherals/InfineaSDKCordova#9]
Using `getConnectedDevicesInfo` crashes if there is no scanner attached to the device. What's the proper way to do this?

**Comment by kyleipcmobile** [comment]
Hi, 

Did you call `Infinea.setDeveloperKey("key");` first? A developer key has to be set in order for other functions to work.

**Comment by jonaszuberbuehler** [comment]
Yes I did.

So `getConnectedDevicesInfo` should work correctly even if there is no scanner attached?

**Comment by kyleipcmobile** [comment]
It would give you empty array. If you iterate, make sure you check if array has items in it. I just ran a test and confirmed thats how it is working without device attached. It didn't crash tho.

**Comment by jonaszuberbuehler** [comment]
Ok, I'll have a look again. Thx anyways!

**Comment by jonaszuberbuehler** [comment]
@kyleipcmobile I could test today again. The problem is that `getConnectedDevicesInfo` always returns an empty array (bug?) and my code was relying on this to enable or disable the scanner.

Question is: how to check if a device is connected to? Or is it safe to ignore it an simply check if cordova and Infinea is defined?

**Comment by kyleipc** [comment]
Have you call `connect` before you call `getConnectedDevicesInfo` ? You can set the callback for `connectionState` to see what state returned from the scanner. If it is 2, it is connected, only then you can call `getConnectedDevicesInfo`

**Comment by jonaszuberbuehler** [comment]
Yes, I'm calling `connect` immediately after `setDeveloperKey`.

Could you answer this: can I safely call any method on Infinea without any device connected? Or is a prior check os some sort needed?

**Comment by kyleipc** [comment]
As long as you set developer key before calling any Infinea methods, you should be ok with or without device connected. If you call any Infinea methods without calling the `setDeveloperKey` first, or the developer key is wrong or mismatch with the current bundle, the app will throw exception. After setting the correct developer key, you can call any other Infinea methods without problem. The error message returned would tell you no device is connected.

**Comment by jonaszuberbuehler** [comment]
Ok cool. Thanks a lot!
